#!/usr/bin/expect

set timeout 2
spawn nc -v 127.0.0.1 6667
send -- "PASS asd\r"
sleep 2
send -- "NICK pizapaco\r"

send -- "USER 1 2 3 :4\r"

expect ": 001 :Welcome to the Internet Relay Network pizapaco!\r"
send -- "JOIN #elpacochannel\r"

send -- "MODE #elpacochannel t+t pepe\r"

#send -- "MODE #elpacochannel +l 10\r"

#send -- "MODE #elpacochannel +k pepe\r"

#send -- "MODE #elpacochannel +p\r"

#send -- "MODE #elpacochannel +s\r"

#send -- "MODE #elpacochannel -s\r"

#send -- "MODE #elpacochannel -s\r"

interact


## ERRORES

## Añadir muchos + o -
